resources:
- name: src
  type: git
  icon: github
  source:
    uri: https://github.com/ajay-iyer-10/screener-pipeline.git
    branch: main

jobs:
- name: my-job
  plan:
    - get: src
      trigger: true
    - task: run
      config:
        platform: linux 
        image_resource:
            type: registry-image
            source: {repository: python, tag: 3.13}
        inputs:
        - name: src
        run:
            path: sh
            args:
                - -c
                - |
                  cd src
                  python3 -m venv venv
                  source venv/bin/activate
                  pip install -r requirements.txt
                  python main.py 


