resources:
- name: src
  type: git
  icon: github
  source:
    uri: https://github.com/ajay-iyer-10/screener-pipeline.git
    branch: main

jobs:
- name: my-job
  plan:
    - get: src
    - task: run
      config:
        platform: linux 
        image_resource:
            type: registry-image
        source:
            repository: python
            tag: "3.13-slim-bookworm" 
        inputs:
        - name: src
        run:
            path: sh
            args:
                - -c
                - |
                  cd src
                  pip install -r requirements.txt
                  python main.py 


